env: "envLocal"
storage_path: "./storage/storage.db"
migration_path: "./migrations"
migration_table: "migrations"
http_server: 
    address: "localhost:8082"
    timeout: 4s
    idle_timeout: 30s
    user: "my_user"
    password: "my_pass"
  